### ISSUE TITLE
可以设置web的权限管理么？

### ISSUE THREAD

**Issue by Xibaibai** [NLPchina/elasticsearch-site#6]
登录http://localhost:8080/login.jsp的时候发现有个login页面哈，
因为正好想做一些权限控制。
想问下大佬应该怎么搞呢。 @shi-yuan

**Comment by shi-yuan** [comment]
能说说具体要做的权限吗？

**Comment by Xibaibai** [comment]
Emmm...  目前打算先把那个登录页面的功能做了.....
就是想问问登录的账号密码是存在哪里的呢.....
需要去改war包里的web项目吗...  如果需要的话有项目地址吗QAQ....

**Comment by shi-yuan** [comment]
嵌入数据库h2

**Comment by shi-yuan** [comment]
用的[Jcoder](https://github.com/NLPchina/Jcoder)
