### ISSUE TITLE
在Elasticsearch-site使用JOIN语句不行!

### ISSUE THREAD

**Issue by Xibaibai** [NLPchina/elasticsearch-site#7]
HTTP 500错误，
Error:{"message":"null is sex , sex is null","ok":false}

？？？？？？？？

这个JOIN语句在Elasticsearch-sql中是可以的... 但是换成site就不行了.... 

兄dei...  空即是色.. 色即是空... 
平时别撸那么多.. 注意保重身体....

看我这么关心你.. 快来帮我看看这个问题... @shi-yuan

**Comment by shi-yuan** [comment]
SQL语句能贴下吗？

**Comment by Xibaibai** [comment]
@shi-yuan 
SELECT * FROM test_scale_add_fans_day1 t1
JOIN scale_add_fans_day1 t2 ON t1.scale_id = t2.scale_id

![image](https://user-images.githubusercontent.com/17681958/44332961-00350f00-a4a0-11e8-9c30-c052c435a7bd.png)

**Comment by shi-yuan** [comment]
我在master上，explain没问题的：
![1](https://user-images.githubusercontent.com/8057153/44334725-f366ea00-a4a4-11e8-987c-82fb50d49c8b.png)

**Comment by Xibaibai** [comment]
我这儿explain也可以呢。。。 就是search的不行。
以下两张图,图1是Elasticsearch-site的,图2是Elasticsearch-sql的.....


@shi-yuan 
![image](https://user-images.githubusercontent.com/17681958/44374322-3b772280-a520-11e8-9c8c-1208d9fdf0bc.png)

![image](https://user-images.githubusercontent.com/17681958/44374428-bb9d8800-a520-11e8-8537-e396f413fedc.png)

**Comment by Xibaibai** [comment]
SELECT * FROM app_day2 t1
JOIN app_day2 t2 ON t1.app_name = t2.app_name


SQL改了一下....  都是为了测试简单的JOIN语句而已.....

**Comment by shi-yuan** [comment]
试试，可行了吗？

**Comment by Xibaibai** [comment]
还是不行阿QAQ......

**Comment by shi-yuan** [comment]
可以的噢
![1](https://user-images.githubusercontent.com/8057153/44457697-86835980-a636-11e8-8d4b-a8784ac964ab.png)
